def import_pods
  pod 'cocos2d', :podspec => 'cocos2d.podspec'
  pod 'ObjectAL-for-iPhone', :path => '../'
end

target :'OALDemo (iOS)' do
  platform :ios, '5.0'
  import_pods
end

target :'OALDemo (OSX)' do
  platform :osx, '10.7'
  import_pods
end
